INSTAGRAM_CLIENT_ID=101675429247586
INSTAGRAM_CLIENT_SECRET=IGQVJXbTZA3eVotSUk3X2VXSGh3QzczRmU5VGVWdXJnZADhkUDNrb2lJWDdqcjFTZAjlabE5QMXZAsbEdkcHhZAdmxPYzNVa2dqMGhwQkVaUDUwVTh3cEZASQUVHX21MWEZADcDZAleGNFNkppYVBxZAmJGZAEhJVQZDZD
INSTAGRAM_REDIRECT_URI=http://www.lovsquad.com/
